//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzl.Common.SMSWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSWebService.SMSSendSoap")]
    public interface SMSSendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSSendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SMSSendMessage(Mzl.Common.SMSWebService.P_SendMessageEntity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSSendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SMSSendMessageAsync(Mzl.Common.SMSWebService.P_SendMessageEntity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SDKSmsCoo_SendSingleSMS_Ext", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SDKSmsCoo_SendSingleSMS_Ext(string Phone, string Content, string Port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SDKSmsCoo_SendSingleSMS_Ext", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SDKSmsCoo_SendSingleSMS_ExtAsync(string Phone, string Content, string Port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SDKSmsCoo_SendSingleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SDKSmsCoo_SendSingleSMS(string Phone, string Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SDKSmsCoo_SendSingleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SDKSmsCoo_SendSingleSMSAsync(string Phone, string Content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageJyTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMessageJyTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageJyTest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendMessageJyTestAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class P_SendMessageEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sendMessageIDField;
        
        private int orderIDField;
        
        private string mobileField;
        
        private string messageBodyField;
        
        private System.DateTime sendTimeField;
        
        private string sendOidField;
        
        private string sendTypeField;
        
        private string httpSMSBackField;
        
        private string successField;
        
        private string sendDeviceField;
        
        private string orderTypeField;
        
        private string titleField;
        
        private bool isMassField;
        
        private int portField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SendMessageID {
            get {
                return this.sendMessageIDField;
            }
            set {
                this.sendMessageIDField = value;
                this.RaisePropertyChanged("SendMessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("OrderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
                this.RaisePropertyChanged("MessageBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("SendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SendOid {
            get {
                return this.sendOidField;
            }
            set {
                this.sendOidField = value;
                this.RaisePropertyChanged("SendOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
                this.RaisePropertyChanged("SendType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HttpSMSBack {
            get {
                return this.httpSMSBackField;
            }
            set {
                this.httpSMSBackField = value;
                this.RaisePropertyChanged("HttpSMSBack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SendDevice {
            get {
                return this.sendDeviceField;
            }
            set {
                this.sendDeviceField = value;
                this.RaisePropertyChanged("SendDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string orderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("orderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsMass {
            get {
                return this.isMassField;
            }
            set {
                this.isMassField = value;
                this.RaisePropertyChanged("IsMass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("Port");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSSendSoapChannel : Mzl.Common.SMSWebService.SMSSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSendSoapClient : System.ServiceModel.ClientBase<Mzl.Common.SMSWebService.SMSSendSoap>, Mzl.Common.SMSWebService.SMSSendSoap {
        
        public SMSSendSoapClient() {
        }
        
        public SMSSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SMSSendMessage(Mzl.Common.SMSWebService.P_SendMessageEntity entity) {
            return base.Channel.SMSSendMessage(entity);
        }
        
        public System.Threading.Tasks.Task<string> SMSSendMessageAsync(Mzl.Common.SMSWebService.P_SendMessageEntity entity) {
            return base.Channel.SMSSendMessageAsync(entity);
        }
        
        public int SDKSmsCoo_SendSingleSMS_Ext(string Phone, string Content, string Port) {
            return base.Channel.SDKSmsCoo_SendSingleSMS_Ext(Phone, Content, Port);
        }
        
        public System.Threading.Tasks.Task<int> SDKSmsCoo_SendSingleSMS_ExtAsync(string Phone, string Content, string Port) {
            return base.Channel.SDKSmsCoo_SendSingleSMS_ExtAsync(Phone, Content, Port);
        }
        
        public int SDKSmsCoo_SendSingleSMS(string Phone, string Content) {
            return base.Channel.SDKSmsCoo_SendSingleSMS(Phone, Content);
        }
        
        public System.Threading.Tasks.Task<int> SDKSmsCoo_SendSingleSMSAsync(string Phone, string Content) {
            return base.Channel.SDKSmsCoo_SendSingleSMSAsync(Phone, Content);
        }
        
        public string SendMessageJyTest() {
            return base.Channel.SendMessageJyTest();
        }
        
        public System.Threading.Tasks.Task<string> SendMessageJyTestAsync() {
            return base.Channel.SendMessageJyTestAsync();
        }
    }
}
