//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzl.BLL.Flight.IBEService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBEService.SearchFlightSoap")]
    public interface SearchFlightSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFiight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[] SearchFiight(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFiight", ReplyAction="*")]
        System.Threading.Tasks.Task<Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[]> SearchFiightAsync(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFiightOffLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[] SearchFiightOffLine(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFiightOffLine", ReplyAction="*")]
        System.Threading.Tasks.Task<Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[]> SearchFiightOffLineAsync(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFiight_ZHX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[] SearchFiight_ZHX(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchFiight_ZHX", ReplyAction="*")]
        System.Threading.Tasks.Task<Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[]> SearchFiight_ZHXAsync(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoIBEPnrSeat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DoIBEPnrSeat(int orderid, string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoIBEPnrSeat", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DoIBEPnrSeatAsync(int orderid, string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoIBEPnrSeatByCorp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DoIBEPnrSeatByCorp(int orderid, string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoIBEPnrSeatByCorp", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DoIBEPnrSeatByCorpAsync(int orderid, string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePnr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeletePnr(string pnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePnr", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeletePnrAsync(string pnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RAWOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RAWOrder(string UserName, string ins, string UserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RAWOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RAWOrderAsync(string UserName, string ins, string UserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoPatA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal DoPatA(string dport, string aport, string flightNo, string airType, string airClass, System.DateTime tackOffTime, System.DateTime arrivalTime, string cityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoPatA", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> DoPatAAsync(string dport, string aport, string flightNo, string airType, string airClass, System.DateTime tackOffTime, System.DateTime arrivalTime, string cityCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Flt_SearchFlightModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rPHField;
        
        private string airlineNoField;
        
        private string flightNoField;
        
        private string airlineDescField;
        
        private string tackOffDateField;
        
        private string tackOffTimeField;
        
        private string tackOffDateAddField;
        
        private string arrivalsDateField;
        
        private string arrivalsTimeField;
        
        private string arrivalsDateAddField;
        
        private string mealField;
        
        private string mealIDField;
        
        private string dportCodeField;
        
        private string aportCodeField;
        
        private string dportNameField;
        
        private string dportName_ENField;
        
        private string aportNameField;
        
        private string aportName_ENField;
        
        private string dportCityNameField;
        
        private string dportCityCodeField;
        
        private string aportCityNameField;
        
        private string aportCityCodeField;
        
        private string oilFeeField;
        
        private string taxFeeField;
        
        private string starAirPortsonField;
        
        private string endAirPortsonField;
        
        private string passByField;
        
        private int passByIntField;
        
        private string airTypeField;
        
        private string yPriceField;
        
        private string cPriceField;
        
        private string fPriceField;
        
        private string sharedFlightNoField;
        
        private bool isSharedField;
        
        private Flt_SearchFlightDetailModel[] detailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RPH {
            get {
                return this.rPHField;
            }
            set {
                this.rPHField = value;
                this.RaisePropertyChanged("RPH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AirlineNo {
            get {
                return this.airlineNoField;
            }
            set {
                this.airlineNoField = value;
                this.RaisePropertyChanged("AirlineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FlightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
                this.RaisePropertyChanged("FlightNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AirlineDesc {
            get {
                return this.airlineDescField;
            }
            set {
                this.airlineDescField = value;
                this.RaisePropertyChanged("AirlineDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TackOffDate {
            get {
                return this.tackOffDateField;
            }
            set {
                this.tackOffDateField = value;
                this.RaisePropertyChanged("TackOffDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TackOffTime {
            get {
                return this.tackOffTimeField;
            }
            set {
                this.tackOffTimeField = value;
                this.RaisePropertyChanged("TackOffTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TackOffDateAdd {
            get {
                return this.tackOffDateAddField;
            }
            set {
                this.tackOffDateAddField = value;
                this.RaisePropertyChanged("TackOffDateAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ArrivalsDate {
            get {
                return this.arrivalsDateField;
            }
            set {
                this.arrivalsDateField = value;
                this.RaisePropertyChanged("ArrivalsDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ArrivalsTime {
            get {
                return this.arrivalsTimeField;
            }
            set {
                this.arrivalsTimeField = value;
                this.RaisePropertyChanged("ArrivalsTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ArrivalsDateAdd {
            get {
                return this.arrivalsDateAddField;
            }
            set {
                this.arrivalsDateAddField = value;
                this.RaisePropertyChanged("ArrivalsDateAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Meal {
            get {
                return this.mealField;
            }
            set {
                this.mealField = value;
                this.RaisePropertyChanged("Meal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MealID {
            get {
                return this.mealIDField;
            }
            set {
                this.mealIDField = value;
                this.RaisePropertyChanged("MealID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DportCode {
            get {
                return this.dportCodeField;
            }
            set {
                this.dportCodeField = value;
                this.RaisePropertyChanged("DportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AportCode {
            get {
                return this.aportCodeField;
            }
            set {
                this.aportCodeField = value;
                this.RaisePropertyChanged("AportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DportName {
            get {
                return this.dportNameField;
            }
            set {
                this.dportNameField = value;
                this.RaisePropertyChanged("DportName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DportName_EN {
            get {
                return this.dportName_ENField;
            }
            set {
                this.dportName_ENField = value;
                this.RaisePropertyChanged("DportName_EN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AportName {
            get {
                return this.aportNameField;
            }
            set {
                this.aportNameField = value;
                this.RaisePropertyChanged("AportName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AportName_EN {
            get {
                return this.aportName_ENField;
            }
            set {
                this.aportName_ENField = value;
                this.RaisePropertyChanged("AportName_EN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DportCityName {
            get {
                return this.dportCityNameField;
            }
            set {
                this.dportCityNameField = value;
                this.RaisePropertyChanged("DportCityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DportCityCode {
            get {
                return this.dportCityCodeField;
            }
            set {
                this.dportCityCodeField = value;
                this.RaisePropertyChanged("DportCityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string AportCityName {
            get {
                return this.aportCityNameField;
            }
            set {
                this.aportCityNameField = value;
                this.RaisePropertyChanged("AportCityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string AportCityCode {
            get {
                return this.aportCityCodeField;
            }
            set {
                this.aportCityCodeField = value;
                this.RaisePropertyChanged("AportCityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OilFee {
            get {
                return this.oilFeeField;
            }
            set {
                this.oilFeeField = value;
                this.RaisePropertyChanged("OilFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string TaxFee {
            get {
                return this.taxFeeField;
            }
            set {
                this.taxFeeField = value;
                this.RaisePropertyChanged("TaxFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string StarAirPortson {
            get {
                return this.starAirPortsonField;
            }
            set {
                this.starAirPortsonField = value;
                this.RaisePropertyChanged("StarAirPortson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string EndAirPortson {
            get {
                return this.endAirPortsonField;
            }
            set {
                this.endAirPortsonField = value;
                this.RaisePropertyChanged("EndAirPortson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string PassBy {
            get {
                return this.passByField;
            }
            set {
                this.passByField = value;
                this.RaisePropertyChanged("PassBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int PassByInt {
            get {
                return this.passByIntField;
            }
            set {
                this.passByIntField = value;
                this.RaisePropertyChanged("PassByInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string AirType {
            get {
                return this.airTypeField;
            }
            set {
                this.airTypeField = value;
                this.RaisePropertyChanged("AirType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string YPrice {
            get {
                return this.yPriceField;
            }
            set {
                this.yPriceField = value;
                this.RaisePropertyChanged("YPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CPrice {
            get {
                return this.cPriceField;
            }
            set {
                this.cPriceField = value;
                this.RaisePropertyChanged("CPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string FPrice {
            get {
                return this.fPriceField;
            }
            set {
                this.fPriceField = value;
                this.RaisePropertyChanged("FPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string SharedFlightNo {
            get {
                return this.sharedFlightNoField;
            }
            set {
                this.sharedFlightNoField = value;
                this.RaisePropertyChanged("SharedFlightNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool IsShared {
            get {
                return this.isSharedField;
            }
            set {
                this.isSharedField = value;
                this.RaisePropertyChanged("IsShared");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=34)]
        public Flt_SearchFlightDetailModel[] DetailList {
            get {
                return this.detailListField;
            }
            set {
                this.detailListField = value;
                this.RaisePropertyChanged("DetailList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Flt_SearchFlightDetailModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sequenceField;
        
        private string classField;
        
        private string classDescField;
        
        private string classDesc_ENField;
        
        private string fatherClassField;
        
        private string facePriceField;
        
        private string salePriceField;
        
        private string baseFacePriceField;
        
        private string baseFacePriceTypeField;
        
        private string seatNumberField;
        
        private string ruleDescField;
        
        private string rateField;
        
        private string fRateField;
        
        private string taxFeeField;
        
        private string oilFeeField;
        
        private string modDesField;
        
        private string endDesField;
        
        private string retDesField;
        
        private string isModField;
        
        private string isEndField;
        
        private string isRetField;
        
        private string priceTypeField;
        
        private string priceTypeDesField;
        
        private string serviceFeeField;
        
        private string nightServicefeeField;
        
        private int serviceFeeTypeField;
        
        private string isViolateField;
        
        private string violateNPolicyValLField;
        
        private string violateNPolicyValLDescField;
        
        private string violateNPolicyValTField;
        
        private string violateNPolicyValTDescField;
        
        private string violateNPolicyValRField;
        
        private string violateNPolicyValRDescField;
        
        private string violateNPolicyValYField;
        
        private string violateNPolicyValYDescField;
        
        private string b2GRuleIdField;
        
        private string b2GFareBasisField;
        
        private bool hasB2GPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClassDesc {
            get {
                return this.classDescField;
            }
            set {
                this.classDescField = value;
                this.RaisePropertyChanged("ClassDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClassDesc_EN {
            get {
                return this.classDesc_ENField;
            }
            set {
                this.classDesc_ENField = value;
                this.RaisePropertyChanged("ClassDesc_EN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FatherClass {
            get {
                return this.fatherClassField;
            }
            set {
                this.fatherClassField = value;
                this.RaisePropertyChanged("FatherClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FacePrice {
            get {
                return this.facePriceField;
            }
            set {
                this.facePriceField = value;
                this.RaisePropertyChanged("FacePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
                this.RaisePropertyChanged("SalePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BaseFacePrice {
            get {
                return this.baseFacePriceField;
            }
            set {
                this.baseFacePriceField = value;
                this.RaisePropertyChanged("BaseFacePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BaseFacePriceType {
            get {
                return this.baseFacePriceTypeField;
            }
            set {
                this.baseFacePriceTypeField = value;
                this.RaisePropertyChanged("BaseFacePriceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SeatNumber {
            get {
                return this.seatNumberField;
            }
            set {
                this.seatNumberField = value;
                this.RaisePropertyChanged("SeatNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RuleDesc {
            get {
                return this.ruleDescField;
            }
            set {
                this.ruleDescField = value;
                this.RaisePropertyChanged("RuleDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FRate {
            get {
                return this.fRateField;
            }
            set {
                this.fRateField = value;
                this.RaisePropertyChanged("FRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TaxFee {
            get {
                return this.taxFeeField;
            }
            set {
                this.taxFeeField = value;
                this.RaisePropertyChanged("TaxFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string OilFee {
            get {
                return this.oilFeeField;
            }
            set {
                this.oilFeeField = value;
                this.RaisePropertyChanged("OilFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ModDes {
            get {
                return this.modDesField;
            }
            set {
                this.modDesField = value;
                this.RaisePropertyChanged("ModDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string EndDes {
            get {
                return this.endDesField;
            }
            set {
                this.endDesField = value;
                this.RaisePropertyChanged("EndDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string RetDes {
            get {
                return this.retDesField;
            }
            set {
                this.retDesField = value;
                this.RaisePropertyChanged("RetDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string isMod {
            get {
                return this.isModField;
            }
            set {
                this.isModField = value;
                this.RaisePropertyChanged("isMod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string isEnd {
            get {
                return this.isEndField;
            }
            set {
                this.isEndField = value;
                this.RaisePropertyChanged("isEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string isRet {
            get {
                return this.isRetField;
            }
            set {
                this.isRetField = value;
                this.RaisePropertyChanged("isRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
                this.RaisePropertyChanged("PriceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PriceTypeDes {
            get {
                return this.priceTypeDesField;
            }
            set {
                this.priceTypeDesField = value;
                this.RaisePropertyChanged("PriceTypeDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ServiceFee {
            get {
                return this.serviceFeeField;
            }
            set {
                this.serviceFeeField = value;
                this.RaisePropertyChanged("ServiceFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string NightServicefee {
            get {
                return this.nightServicefeeField;
            }
            set {
                this.nightServicefeeField = value;
                this.RaisePropertyChanged("NightServicefee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int ServiceFeeType {
            get {
                return this.serviceFeeTypeField;
            }
            set {
                this.serviceFeeTypeField = value;
                this.RaisePropertyChanged("ServiceFeeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string IsViolate {
            get {
                return this.isViolateField;
            }
            set {
                this.isViolateField = value;
                this.RaisePropertyChanged("IsViolate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ViolateNPolicyValL {
            get {
                return this.violateNPolicyValLField;
            }
            set {
                this.violateNPolicyValLField = value;
                this.RaisePropertyChanged("ViolateNPolicyValL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string ViolateNPolicyValLDesc {
            get {
                return this.violateNPolicyValLDescField;
            }
            set {
                this.violateNPolicyValLDescField = value;
                this.RaisePropertyChanged("ViolateNPolicyValLDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string ViolateNPolicyValT {
            get {
                return this.violateNPolicyValTField;
            }
            set {
                this.violateNPolicyValTField = value;
                this.RaisePropertyChanged("ViolateNPolicyValT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ViolateNPolicyValTDesc {
            get {
                return this.violateNPolicyValTDescField;
            }
            set {
                this.violateNPolicyValTDescField = value;
                this.RaisePropertyChanged("ViolateNPolicyValTDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ViolateNPolicyValR {
            get {
                return this.violateNPolicyValRField;
            }
            set {
                this.violateNPolicyValRField = value;
                this.RaisePropertyChanged("ViolateNPolicyValR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ViolateNPolicyValRDesc {
            get {
                return this.violateNPolicyValRDescField;
            }
            set {
                this.violateNPolicyValRDescField = value;
                this.RaisePropertyChanged("ViolateNPolicyValRDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ViolateNPolicyValY {
            get {
                return this.violateNPolicyValYField;
            }
            set {
                this.violateNPolicyValYField = value;
                this.RaisePropertyChanged("ViolateNPolicyValY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string ViolateNPolicyValYDesc {
            get {
                return this.violateNPolicyValYDescField;
            }
            set {
                this.violateNPolicyValYDescField = value;
                this.RaisePropertyChanged("ViolateNPolicyValYDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string B2GRuleId {
            get {
                return this.b2GRuleIdField;
            }
            set {
                this.b2GRuleIdField = value;
                this.RaisePropertyChanged("B2GRuleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string B2GFareBasis {
            get {
                return this.b2GFareBasisField;
            }
            set {
                this.b2GFareBasisField = value;
                this.RaisePropertyChanged("B2GFareBasis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool HasB2GPrice {
            get {
                return this.hasB2GPriceField;
            }
            set {
                this.hasB2GPriceField = value;
                this.RaisePropertyChanged("HasB2GPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchFlightSoapChannel : Mzl.BLL.Flight.IBEService.SearchFlightSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchFlightSoapClient : System.ServiceModel.ClientBase<Mzl.BLL.Flight.IBEService.SearchFlightSoap>, Mzl.BLL.Flight.IBEService.SearchFlightSoap {
        
        public SearchFlightSoapClient() {
        }
        
        public SearchFlightSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchFlightSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchFlightSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchFlightSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[] SearchFiight(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID) {
            return base.Channel.SearchFiight(dport, aport, tackOffTime, searchAirlineNo, corpID);
        }
        
        public System.Threading.Tasks.Task<Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[]> SearchFiightAsync(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID) {
            return base.Channel.SearchFiightAsync(dport, aport, tackOffTime, searchAirlineNo, corpID);
        }
        
        public Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[] SearchFiightOffLine(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID) {
            return base.Channel.SearchFiightOffLine(dport, aport, tackOffTime, searchAirlineNo, corpID);
        }
        
        public System.Threading.Tasks.Task<Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[]> SearchFiightOffLineAsync(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID) {
            return base.Channel.SearchFiightOffLineAsync(dport, aport, tackOffTime, searchAirlineNo, corpID);
        }
        
        public Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[] SearchFiight_ZHX(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID) {
            return base.Channel.SearchFiight_ZHX(dport, aport, tackOffTime, searchAirlineNo, corpID);
        }
        
        public System.Threading.Tasks.Task<Mzl.BLL.Flight.IBEService.Flt_SearchFlightModel[]> SearchFiight_ZHXAsync(string dport, string aport, string tackOffTime, string searchAirlineNo, string corpID) {
            return base.Channel.SearchFiight_ZHXAsync(dport, aport, tackOffTime, searchAirlineNo, corpID);
        }
        
        public string DoIBEPnrSeat(int orderid, string oid) {
            return base.Channel.DoIBEPnrSeat(orderid, oid);
        }
        
        public System.Threading.Tasks.Task<string> DoIBEPnrSeatAsync(int orderid, string oid) {
            return base.Channel.DoIBEPnrSeatAsync(orderid, oid);
        }
        
        public string DoIBEPnrSeatByCorp(int orderid, string oid) {
            return base.Channel.DoIBEPnrSeatByCorp(orderid, oid);
        }
        
        public System.Threading.Tasks.Task<string> DoIBEPnrSeatByCorpAsync(int orderid, string oid) {
            return base.Channel.DoIBEPnrSeatByCorpAsync(orderid, oid);
        }
        
        public string DeletePnr(string pnr) {
            return base.Channel.DeletePnr(pnr);
        }
        
        public System.Threading.Tasks.Task<string> DeletePnrAsync(string pnr) {
            return base.Channel.DeletePnrAsync(pnr);
        }
        
        public string RAWOrder(string UserName, string ins, string UserPwd) {
            return base.Channel.RAWOrder(UserName, ins, UserPwd);
        }
        
        public System.Threading.Tasks.Task<string> RAWOrderAsync(string UserName, string ins, string UserPwd) {
            return base.Channel.RAWOrderAsync(UserName, ins, UserPwd);
        }
        
        public decimal DoPatA(string dport, string aport, string flightNo, string airType, string airClass, System.DateTime tackOffTime, System.DateTime arrivalTime, string cityCode) {
            return base.Channel.DoPatA(dport, aport, flightNo, airType, airClass, tackOffTime, arrivalTime, cityCode);
        }
        
        public System.Threading.Tasks.Task<decimal> DoPatAAsync(string dport, string aport, string flightNo, string airType, string airClass, System.DateTime tackOffTime, System.DateTime arrivalTime, string cityCode) {
            return base.Channel.DoPatAAsync(dport, aport, flightNo, airType, airClass, tackOffTime, arrivalTime, cityCode);
        }
    }
}
